on: 
  push:
    tags:
      - 'v*'

name: Release

jobs:
  release:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: any-desktop
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run semantic-release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

create-github-release:
  name: Create Github Release
  runs-on: desktop
  needs: publish
  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create Release Notes
      uses: actions/github-script@v0.0.2

      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script:
          await github.request('POST /repos/${{github.repository}}/releases' , {
            tag_name: "${{github.ref}}",
            generate_release_notes: true
          });
